networks:
  internal-network:
services:
  service:
    networks:
      - internal-network
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:88"
  db:
    networks:
      - internal-network
    container_name: postgresdb
    image: postgres:16
    command: -db-ssl-mode=allow
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./postgres-custom-config:/etc/postgresql
    ports:
      - "5432:52"
    env_file:
      - .env
  traefik:
    command:
      - "--ping=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.filename=/etc/traefik.conf"
    networks:
      - internal-network
    container_name: traefik
    image: traefik:3.1.3
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/traefik/traefik.conf:/etc/traefik.conf
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
