version: '3'
services:
  service:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    container_name: postgresdb
    image: postgres:16
    command: -db-ssl-mode=allow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./postgres-custom-config:/etc/postgresql
    env_file:
      - .env
